### ISSUE TITLE
Still need some help going live

### ISSUE THREAD

**Issue by ashtastic** [ashtastic/portfolio#1]
Hey @ericadamski!

So my website still wont go live with ashtastic.ca — I think it has to do with my Cloudflare. I was originally on the fastmail free trial, so over the holidays I switched over to the forwarding service on Hover and paid the 5$. I reset my DNS settings in order to get rid of the fastmail settings. Since then my website hasn't gone live and the email isn't linked up. I've gone over Thomas' notes and can't figure it out. I just checked my Cloudflare DNS settings and there's errors there:

<img width="996" alt="screen shot 2017-01-10 at 12 52 07 pm" src="https://cloud.githubusercontent.com/assets/10467656/21817976/13554cc0-d734-11e6-9f41-9182954c6a60.png">

 So, I think I've figured out the problem, but I don't know how to fix it. Anyway you could help me out through github? If not, I'll sit down with you next class if we have time.

**Comment by ericadamski** [comment]
@ashtastic I think it would be much simpler if we could sit down if it can wait that long :)

**Comment by ashtastic** [comment]
Ya, I think so too. See you next week!

**Comment by ericadamski** [comment]
See you!
